### ISSUE TITLE
请问Actions构建后的html在哪？

### ISSUE THREAD

**Issue by chengzhnag** [LasyIsLazy/blog#45]
你好，为啥访问https://lasyislazy.github.io/blog/有你构建后的html，但是在这个仓库里面没有看到，不是用的github-pages吗

**Comment by LasyIsLazy** [comment]
通过workflow构建后，将生成的产物上传到github-pages。通过[upload-pages-artifact](https://github.com/actions/upload-pages-artifact)，不需要保留构建产物。
